/*=============================================================================
   WARNING!!  This file is overwritten by the UIStyler each time the Styler 
   file is saved.
  
  
        Filename:  opu_cut_param.h
  
        This file was generated by the NX User Interface Styler
        Created by: ChudoyakovEB68
        Version: NX 4
              Date: 02-27- 8
              Time: 17:50
  
   This include file is overwritten each time the UIStyler dialog is
   saved.  Any modifications to this file will be lost.
==============================================================================*/
 
 
#ifndef OPU_CUT_PARAM_H_INCLUDED
#define OPU_CUT_PARAM_H_INCLUDED
 
#include <uf.h> 
#include <uf_defs.h>
#include <uf_styler.h> 


#ifdef __cplusplus
extern "C" {
#endif


/*------------------ UIStyler Dialog Definitions  ------------------- */
/* The following values are definitions into your UIStyler dialog.    */
/* These values will allow you to modify existing objects within your */
/* dialog.   They work directly with the NX Open API,                 */
/* UF_STYLER_ask_value, UF_STYLER_ask_values, and UF_STYLER_set_value.*/
/*------------------------------------------------------------------- */
 
#define MT_STOCK_BITMAP                ("STOCK_BITMAP")
#define MT_STOCK_TOG                   ("STOCK_TOG")
#define MT_STOCK_REAL_1                ("STOCK_REAL_1")
#define MT_STOCK_REAL_2                ("STOCK_REAL_2")
#define MT_STOCK_REAL_3                ("STOCK_REAL_3")
#define MT_STOCK_REAL_4                ("STOCK_REAL_4")
#define MT_STOCK_REAL_5                ("STOCK_REAL_5")
#define MT_GR_STOCK_BEG_7              ("GR_STOCK_BEG_7")
#define MT_STOCK_TOG_FINISH_PAS        ("STOCK_TOG_FINISH_PAS")
#define MT_STOCK_REAL_6                ("STOCK_REAL_6")
#define MT_GR_END_8                    ("GR_END_8")
#define MT_SEP                         ("SEP")
#define MT_STOCK_REAL_7                ("STOCK_REAL_7")
#define MT_STOCK_REAL_8                ("STOCK_REAL_8")
#define MT_DIALOG_OBJECT_COUNT         ( 14 )
 

/*---------------- UIStyler Callback Prototypes --------------- */
/* The following function prototypes define the callbacks       */
/* specified in your UIStyler built dialog.  You are REQUIRED to*/
/* create the associated function for each prototype.  You must */
/* use the same function name and parameter list when creating  */
/* your callback function.                                      */
/*------------------------------------------------------------- */

int MT_construct_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int MT_apply_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int MT_stock_tog_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int MT_real_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int MT_stock_finish_tog_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);




#ifdef __cplusplus
}
#endif



#endif /* OPU_CUT_PARAM_H_INCLUDED */
